name: Deploy Vue App to AWS S3

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup NodeJS in our environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm install
          npm run build

      # Syncs the 'dist' folder from buildng the Vue app with an S3 bucket

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # replace this with your aws-region

      - name: Upload files to S3 with AWS CLI
        run: |
          aws s3 sync dist/ s3://app.nubadoo.com --delete

      # Clears the CloudFront cache so new requests will receive the latest version of your app
      #- name: Invalidate Cloudfront
      #  uses: chetan/invalidate-cloudfront-action@v1.3
      #  env:
      #    DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      #    PATHS: '/*'
      #    AWS_REGION: 'us-east-1'
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
