name: Build + Test + Deploy FE App S3

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Run manually (for admins and testing)
  workflow_dispatch:

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup CI environment
        run: make build-ci-env

      - name: Start CI environment
        run: make start-ci-env

      - name: Start tests
        run: make start-ci-test

      - name: Deploy
        run: echo "add deployment steps from now on. Remaining steps will be running after the previous steps have passed."

  deploy:
    needs: build-and-test-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup NodeJS in our environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      # Runs a set of commands using the runners shell
      - name: Node install and build
        run: |
          npm install
          npm run build

      # Syncs the 'dist' folder from buildng the Vue app with an S3 bucket
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # replace this with your aws-region

      - name: Upload files to S3 with AWS CLI
        run: |
          aws s3 sync dist/ s3://app.nubadoo.com --delete

  refresh-cache:
    needs: deploy
    runs-on: ubuntu-latest
    steps:    
      #Clears the CloudFront cache so new requests will receive the latest version of your app
      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
